---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    # ── Control Plane ───────────────────────
    masters:
      hosts:
        k8-master1-dev:
          ansible_host: 172.16.1.20
        k8-master2-dev:
          ansible_host: 172.16.1.21
        k8-master3-dev:
          ansible_host: 172.16.1.22

    # ── Workers ─────────────────────────────
    workers:
      hosts:
        k8-worker1-dev:
          ansible_host: 172.16.1.23
        k8-worker2-dev:
          ansible_host: 172.16.1.24
        k8-worker3-dev:
          ansible_host: 172.16.1.25
        k8-worker4-dev:
          ansible_host: 172.16.1.26
        k8-worker5-dev:
          ansible_host: 172.16.1.27

    # ── Combined group ──────────────────────
    kubernetes:
      children:
        masters:
        workers:
